# Generated by Django 3.0.5 on 2020-05-28 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200520_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['added_on'], 'permissions': (('can_delete_book', 'Can delete book'),)},
        ),
    ]
