# Generated by Django 3.0.5 on 2020-06-10 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200602_2251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_add_book', 'Can add book'),)},
        ),
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['added_on'], 'permissions': (('can_delete_book', 'Can delete book instance'),)},
        ),
    ]
