# Generated by Django 3.0.5 on 2020-07-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20200728_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='summary',
            field=models.TextField(blank=True, help_text='Enter a brief description of the book', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='user_book_review',
            field=models.TextField(blank=True, help_text='Enter your review here', max_length=1000, null=True),
        ),
    ]
